### ISSUE TITLE
Allow contributions/pull requests?

### ISSUE THREAD

**Issue by mfcallahan** [petedannemann/gis-programming-roadmap#2]
Hello, would you consider allowing contributions to the GIS-Programming-Roadmap?  I think it's very helpful and very well-organized.  I'd like to add some content for learning ArcGIS Pro Add-Ins and .NET Core (which is mentioned in "Backend Web Development" but no links are provided).

**Comment by mfcallahan** [comment]
I'm unable to push to this GIS-Programming-Roadmap repo, are you able to add me as a collaborator?

**Comment by phlpeterdannemann** [comment]
No, submit a pull request. 

1. Fork this repo
2. Make your changes
3. Visit this repos 'Pull Request' tab, click 'New Pull Request'
4. Select your repo and submit the PR

**Comment by petedannemann** [comment]
No, submit a pull request. 

1. Fork this repo
2. Make your changes
3. Visit this repos 'Pull Request' tab, click 'New Pull Request'
4. Select your repo and submit the PR
